### ISSUE TITLE
Time to finish in BW4T logs is total time running not time taken on logged run.

### ISSUE THREAD

**Issue by jzvandenoever** [eishub/BW4T#232]
The log entry about time looks like this after several runs even if the particular runtime is just under 1 minute per set of solving the sequence:

> Time to finish sequence is 3 minutes and 5 seconds

The same as the total time the server has been running. 

> total time is 3 minutes and 26 seconds

**Comment by Venorcis** [comment]
Fixed in develop, try this server build: [bw4t-server-3.9.2-SNAPSHOT.zip](https://github.com/eishub/BW4T/files/2302463/bw4t-server-3.9.2-SNAPSHOT.zip)
